routes/admin.php
use App\Http\Controllers\Admin\BannerTypeController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\Admin\GCurrencyInfoController;
use App\Http\Controllers\FaqQuestionAnswerController;
use App\Http\Controllers\FaqCategoryController;

//Todo Add more security
Route::get('/login', [AuthenticatedSessionController::class, 'create'])
    ->middleware('guest')
    ->name('admin.login');

Route::post('/login', [AuthenticatedSessionController::class, 'store'])
    ->middleware('guest');

/** Authenticated user sections */
Route::prefix('panel')->middleware(['is_authenticated'])->name('admin.')->group(function () {
    Route::get('/logout', [AuthenticatedSessionController::class, 'destroy'])
        ->name('logout');
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::prefix('game')->group(function () {
        //show all game users
        Route::get('/users', [GameController::class, 'users'])->name('game-users.index');
        Route::get('/scores/{user}', [GameController::class, 'scores'])->name('game-users.scores');
        Route::delete('/scores/delete/{score}', [GameController::class, 'deleteScores'])->name('game-users.scores.destroy');

    });

    Route::prefix('global-currencies')->name('global-currencies.')->group(function () {
        //show all global currencies
        Route::get('/', [GlobalCurrencyController::class, 'index'])->name('index');
        //create and store route
        Route::get('/create', [GlobalCurrencyController::class, 'create'])->name('create');
        Route::post('/create', [GlobalCurrencyController::class, 'store'])->name('store');
        //show one global currency route
        Route::get('/show/{currency}', [GlobalCurrencyController::class, 'show'])->name('show');
        //edit and update route
        Route::get('/edit/{currency}/', [GlobalCurrencyController::class, 'edit'])->name('edit');
        Route::post('/edit/{currency}', [GlobalCurrencyController::class, 'update'])->name('update');
        //destroy one global currency
        Route::delete('/delete/{currency}', [GlobalCurrencyController::class, 'destroy'])->name('destroy');
        //Todo:show banners with related gc
        Route::get('/show_banner_gc/{global_currency_id}', [BannerGCController::class, 'showGCWithBanners'])->name('show_banner_gc');
        Route::get('/add_banners/{global_currency_id}', [BannerGCController::class, 'selectBanners'])->name('add_banners');
        Route::post('/add_banners/{global_currency_id}', [BannerGCController::class, 'addBannerToGlobalCurrency']);
        Route::get('attach_banner/{global_currency_id}', [GlobalCurrencyController::class, 'attachBanner']);
        Route::get('/make_hidden/{global_currency_id}', [GlobalCurrencyController::class, 'makeGlobalCurrencyHidden'])->name('make_hidden');

    });

    //IntervalController
    Route::prefix('currency_change_percent')->name('currency_change_percent.')->group(function () {
        Route::get('/', [CurrencyChangeController::class, 'show'])->name('show');
        Route::get('/create', [CurrencyChangeController::class, 'create'])->name('create');
        Route::post('/create', [CurrencyChangeController::class, 'store'])->name('store');
        Route::get('/edit/{currencyChangePercent}', [CurrencyChangeController::class, 'edit'])->name('edit');
        Route::put('/edit/{currencyChangePercent}', [CurrencyChangeController::class, 'update'])->name('update');
        Route::get('/delete/{currencyChangePercent}', [CurrencyChangeController::class, 'destroy'])->name('destroy');
    });

    Route::prefix('intervals')->name('intervals.')->group(function () {
        Route::get('/', [IntervalController::class, 'show'])->name('show');
        Route::get('/create', [IntervalController::class, 'create'])->name('create');
        Route::post('/create', [IntervalController::class, 'store'])->name('store');
        Route::get('/edit/{interval}', [IntervalController::class, 'edit'])->name('edit');
        Route::put('/edit/{interval}', [IntervalController::class, 'update'])->name('update');
        Route::get('/delete/{interval}', [IntervalController::class, 'destroy'])->name('destroy');
    });

    Route::prefix('banner')->name('banner.')->group(function () {

        Route::prefix('types')->name('types.')->group(function () {
            Route::get('/', [BannerTypeController::class, 'show'])->name('show');
            Route::get('/create', [BannerTypeController::class, 'create'])->name('create');
            Route::post('/create', 'BannerTypeController@store')->name('store');
            Route::get('/edit/{bannerType}', 'BannerTypeController@edit')->name('edit');
            Route::put('/edit/{bannerType}', 'BannerTypeController@update')->name('update');
            Route::get('/delete/{bannerType}', 'BannerTypeController@destroy')->name('destroy');
        });

        Route::get('/', [BannerController::class, 'show'])->name('show');
        Route::get('active_banners', [BannerController::class, 'showActiveBanners'])->name('active');
        Route::get('create', [BannerController::class, 'create'])->name('create');
        Route::post('create', [BannerController::class, 'add']);
        Route::get('edit/{banner}', [BannerController::class, 'edit'])->name('edit');
        Route::post('edit/{banner}', [BannerController::class, 'update']);
        Route::get('edit2/{banner}', [BannerController::class, 'update2'])->name('edit2');
        Route::get('delete/{banner}', [BannerController::class, 'delete'])->name('delete');
        Route::get('toggle/{banner}', [BannerController::class, 'toggleBanners'])->name('toggle');
        Route::get('slider_toggle/{banner}', [BannerController::class, 'toggleSliderBanners'])->name('toggle-sliders');
        Route::get('add_global_currencies/{banner_id}', [BannerGCController::class, 'selectGlobalCurrencies'])->name('add_global_currencies');
        Route::post('add_global_currencies/{banner_id}', [BannerGCController::class, 'addGlobalCurrencyToBanner']);
    });

//    Route::prefix('faq')->name('faq.')->group(function () {
//
//        Route::prefix('category')->name('category.')->group(function () {
//            Route::get('/', [FaqCategoryController::class, 'show'])->name('show_categories');
//            Route::get('create', [FaqCategoryController::class, 'create'])->name('create');
//            Route::post('create', [FaqCategoryController::class, 'add']);
//            Route::get('edit/{faq_category}', [FaqCategoryController::class, 'edit'])->name('edit');
//            Route::post('edit/{faq_category}', [FaqCategoryController::class, 'update']);
//            Route::get('delete/{faq_category}', [FaqCategoryController::class, 'delete'])->name('delete');
//        });
//
//        Route::prefix('question_answer')->name('question_answer.')->group(function () {
//            Route::get('/', [FaqQuestionAnswerController::class, 'showQuestions'])->name('show_questions');
//            Route::get('create', [FaqQuestionAnswerController::class, 'create'])->name('create');
//            Route::post('create', [FaqQuestionAnswerController::class, 'add']);
//            Route::get('edit/{faq_question_answer}', [FaqQuestionAnswerController::class, 'edit'])->name('edit');
//            Route::post('edit/{faq_question_answer}', [FaqQuestionAnswerController::class, 'update'])->name('update');
//            Route::get('delete/{faq_question_answer}', [FaqQuestionAnswerController::class, 'delete'])->name('delete');
//            Route::get('/selected/{faq_question_answer}', [FaqQuestionAnswerController::class, 'showSelectedQuestion'])->name('feedback');
//
//            Route::prefix('deeplink')->name('deeplink.')->group(function () {
//                Route::get('/create/{id}', [FaqQuestionAnswerController::class, 'createDeeplink'])->name('create');
//                Route::post('/store', [FaqQuestionAnswerController::class, 'storeDeeplink'])->name('store');
//                Route::get('delete/{deeplink_id}', [FaqQuestionAnswerController::class, 'deleteDeeplink'])->name('delete');
//            });
//        });
//    });

    Route::prefix('comments')->name('comments.')->group(function () {
        Route::get('/', [CommentController::class, 'showComments'])->name('show');
        Route::get('/show/survey', [CommentController::class, 'showSurvey'])->name('survey');
        Route::get('/toggle/{comment_id}', [CommentController::class, 'toggleComment'])->name('toggle');
        Route::post('/toggle/multiple', [CommentController::class, 'toggleMultipleComment'])->name('toggle.multiple');
    });

    Route::prefix('trend')->name('trend.')->group(function () {
        Route::get('/', [TrendController::class, 'show'])->name('show');
        Route::get('/create', [TrendController::class, 'create'])->name('create');
        Route::post('/create', [TrendController::class, 'add'])->name('store');
        Route::get('/edit/{id}', [TrendController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [TrendController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [TrendController::class, 'delete'])->name('delete');
    });

    Route::prefix('gainer')->name('gainer.')->group(function () {
        Route::get('/', [GainerController::class, 'show'])->name('show');
        Route::get('/create', [GainerController::class, 'create'])->name('create');
        Route::post('/create', [GainerController::class, 'add'])->name('store');
        Route::get('/edit/{id}', [GainerController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [GainerController::class, 'update'])->name('update');
        Route::get('/delete/{id}', [GainerController::class, 'delete'])->name('delete');
    });

    Route::prefix('looser')->name('looser.')->group(function () {
        Route::get('/', [LooserController::class, 'show'])->name('show');

routes/web.php
<?php

use App\Http\Controllers\API\GlobalCurrencyController;
use App\Http\Controllers\GameController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StorageManagerController;
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/storage/{path}', [StorageManagerController::class, 'showFile'])
    ->where([
        'path' => '.*'
    ])
    ->name('storage.show.file');

Route::get('/exchange/getUserGame',[\App\Http\Controllers\ApiKeyController::class,'gameUser'])->name('gameUser');



Route::get('/exchange/tv_market_global2/{symbol}', [GlobalCurrencyController::class, 'tradingViewBySymbol'])->middleware('s_cache:300');
Route::get('/exchange/tv_market/{pair_id}', [GlobalCurrencyController::class, 'tradingViewByPairId'])->middleware('s_cache:300');
Route::get('exchange/pt1/market',[\App\Http\Controllers\VueController::class,'pwaIndex']);
Route::pattern('ex', '.*');
Route::any('/pt{ex}', [\App\Http\Controllers\VueController::class, 'pwaIndex'])->name('pwa_index');
Route::get('play', function () {
    return redirect('https://ramzinex.com/');
});
Route::prefix('comments_report')->name('comments_report.')->group(function () {
//    Route::get('/report', [CommentController::class, 'getCommentReplies'])->middleware('s_cache:300')->name('report.list');
    Route::POST('/create', [\App\Http\Controllers\API\CommentReportController::class, 'create'])->name('create');
//    Route::POST('/dislike', [CommentController::class, 'dislikeComments'])->name('dislike');
});

Route::pattern('ex', '.*');
Route::any('/register_with_invitation={ex}', [\App\Http\Controllers\ExcelController::class, 'test'])->name('test*');

//Route::pattern('ex', '.*');
Route::get('/test_new_url',[\App\Http\Controllers\ExcelController::class, 'testUrl'])->name('test**');

//Route::get('hiiii',[\App\Http\Controllers\ExcelController::class,'testUrl']);
Route::get('/testLock1',[\App\Http\Controllers\ApiKeyController::class, 'test1'])->name('test1');
Route::get('/testLock2',[\App\Http\Controllers\ApiKeyController::class, 'test2'])->name('test2');
Route::get('/rrrr',function (){
    return 'hii';
})->name('test3');

resources/views/currency_change_percent/create.blade.php
@extends('layouts.appAdmin')
@section('title', 'ایجاد سود و زیان جدید')

@section('desktop')

    @if ( count($errors) > 0)
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    @endif
        @if (session()->has('success'))
            <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif
        @if (session()->has('success'))
            <div class="alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif

    <div class="row">
        <div class="col-xlg-12 col-lg-12">
            <div class="panelGlass minH-240">
                <form action="{{route('admin.currency_change_percent.store')}}" method="POST" class="form-inline" enctype="multipart/form-data">

                   {{csrf_field()}}

                    <div class="form-group pa-10">
                        <label class="control-label mb-10"
                               for="value">مقدار</label>
                        <input type="number" class="form-control"
                               name="value"
                               placeholder="مقدار..." required>
                    </div>

                    <div class="form-group pa-10">

                        <label for="currency_id">نام ارز</label>

                        <select class="form-control" name="global_currency_id" required>
                            @foreach($currencies as $currency)

                                <option value="{{$currency->id}}">
                                    {{$currency->name_en}}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group pa-10">
                        <label for="interval_id">نام اینتروال</label>
                        <select class="form-control" name="interval_id" required>
                            @foreach($intervals as $interval)
                                <option value="{{$interval->id}}">
                                    {{$interval->title_fa}}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="col-md-12 pa-20 text-center">
                        <div class="form-actions mt-10">
                            <button id="update-profile" type="submit"
                                    class="btn btn-primary mr-10 mb-30">
                                ایجاد سود و زیان
                            </button>
                        </div>
                    </div>

                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/currency_change_percent/edit.blade.php
@extends('layouts.appAdmin')
@section('title', 'ویرایش سود و زیان')

@section('desktop')

    @if ( count($errors) > 0)
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    @endif
        @if (session()->has('success'))
            <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif
        @if (session()->has('error'))
            <div class="alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif

    <div class="row">
        <div class="col-xlg-12 col-lg-12">
            <div class="panelGlass minH-240">
                <form action="{{route('admin.currency_change_percent.update',[$currencyChange->id])}}" method="POST" class="form-inline">

                    {{csrf_field()}}

                    @method('PUT')

                    <div class="form-group pa-10">
                        <label class="control-label mb-10"
                               for="value">مقدار</label>
                        <input type="number" class="form-control"
                               name="value" id="value"
                               value="{{$currencyChange->value}}">
                    </div>

                    <div class="form-group pa-10">
                        <label for="currency_id">نام ارز</label>
                        <select  class="form-control" name="currency_id">
                            <option value=""> </option>
                            @foreach($currencies as $currency)
                                <option value="{{$currency->id}}"
                                        @if($currency->id == $currencyChange->global_currency_id) selected = "selected" @endif>
                                    {{$currency->name_en}}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="form-group pa-10">
                        <label for="interval_id">نام اینتروال</label>
                        <select  class="form-control" name="interval_id">
                            <option value=""> </option>
                            @foreach($intervals as $interval)
                                <option value="{{$interval->id}}"
                                        @if($interval->id == $currencyChange->interval_id) selected = "selected" @endif>
                                    {{$interval->title_fa}}
                                </option>
                            @endforeach
                        </select>
                    </div>

                    <div class="col-md-12 pa-20 text-center">
                        <div class="form-actions mt-10">
                            <button id="update-profile" type="submit"
                                    class="btn btn-primary mr-10 mb-30">
                                ویرایش سود و زیان
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
@endsection

resources/views/currency_change_percent/show.blade.php
@extends('layouts.appAdmin')
@section('title', 'نمایش لیست سود و زیان ها')

@section('desktop')

    @if ( count($errors) > 0)
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    @endif
    @if (session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif
    @if ( session()->has('error'))
        <div class="alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif

    <div class="row">
        <div class="col-xlg-12 col-lg-12">
            <div class="panelGlass minH-240">
                <div>
                    <form action="{{route('admin.currency_change_percent.show')}}" method="get" class="form-inline" enctype="multipart/form-data">

                        {{csrf_field()}}

                        <div class="form-group pa-10">
                            <label for="currency_id">نام ارز</label>

                            <select  class="form-control" name="global_currency_id">
                                <option value=""> </option>
                                @foreach($currencies as $currency)
                                    <option value="{{$currency->id}}">
                                        {{$currency->name_en}}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="form-group pa-10">
                            <label for="network_id">نام اینتروال</label>
                            <select  class="form-control" name="network_id">
                                <option value=""> </option>
                                @foreach($intervals as $interval)
                                    <option value="{{$interval->id}}">
                                        {{$interval->title_fa}}
                                    </option>
                                @endforeach
                            </select>
                        </div>

                        <div class="col-md-12 pa-20 text-center">
                            <div class="form-actions mt-10">
                                <button id="update-profile" type="submit"
                                        class="btn btn-primary mr-10 mb-30">
                                    جستجوی نکات سود و زیان
                                </button>
                            </div>
                        </div>

                    </form>

                    <table id="bonusTable" class="table mediumThead">
                        <div class="row">
                            <div class="form-wrap">

                                <thead>
                                <tr>
                                    <th scope="col"> مقدار</th>
                                    <th scope="col"> نام ارز</th>
                                    <th scope="col">نام اینتروال</th>
                                    <th>
                                        <a href="{{route('admin.currency_change_percent.create')}}" class="btn btn-primary">ایجاد نکات معاملات</a>
                                    </th>
                                </tr>
                                </thead>

                                <tbody>
                                @foreach($currencyChangePercent as $change)
                                    <tr>
                                        <td class="text-sm">{{$change->value}}</td>
                                        <td class="text-sm">{{$change->currency->name_en}}</td>
                                        <td class="text-sm">{{$change->interval->title_fa}}</td>
                                        <td class="text-sm">
                                            <a href="{{route('admin.currency_change_percent.update',[$change->id])}}"
                                               class="btn btn-primary">ویرایش</a>

                                            <a href="{{route('admin.currency_change_percent.destroy',[$change->id])}}"
                                               onclick="return confirm('آیا مایل به حذف این فیلد هستید؟')"
                                               class="btn btn-danger">حذف</a>
                                        </td>
                                    </tr>
                                @endforeach
                                </tbody>
                            </div>
                        </div>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {{$currencyChangePercent->links()}}
@endsection