routes/admin.php
<?php

use App\Http\Controllers\Admin\BannerGCController;
use App\Http\Controllers\Admin\CurrencyOHLCController;
use App\Http\Controllers\Admin\GainerController;
use App\Http\Controllers\Admin\LooserController;
use App\Http\Controllers\Admin\TrendController;
use App\Http\Controllers\Admin\TrendingCurrencyController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\GameController;
use App\Jobs\UpdateLeftOverGlobalCurrenciesJob;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Admin\GlobalCurrencyController;
use App\Http\Controllers\CurrencyChangeController;
use App\Http\Controllers\IntervalController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BannerTypeController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\Admin\GCurrencyInfoController;
use App\Http\Controllers\FaqQuestionAnswerController;
use App\Http\Controllers\FaqCategoryController;

//Todo Add more security
Route::get('/login', [AuthenticatedSessionController::class, 'create'])
    ->middleware('guest')
    ->name('admin.login');

Route::post('/login', [AuthenticatedSessionController::class, 'store'])
    ->middleware('guest');

/** Authenticated user sections */
Route::prefix('panel')->middleware(['is_authenticated'])->name('admin.')->group(function () {
    Route::get('/logout', [AuthenticatedSessionController::class, 'destroy'])
        ->name('logout');
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::prefix('game')->group(function () {
        //show all game users
        Route::get('/users', [GameController::class, 'users'])->name('game-users.index');
        Route::get('/scores/{user}', [GameController::class, 'scores'])->name('game-users.scores');
        Route::delete('/scores/delete/{score}', [GameController::class, 'deleteScores'])->name('game-users.scores.destroy');

    });

    Route::prefix('global-currencies')->name('global-currencies.')->group(function () {
        //show all global currencies
        Route::get('/', [GlobalCurrencyController::class, 'index'])->name('index');
        //create and store route
        Route::get('/create', [GlobalCurrencyController::class, 'create'])->name('create');
        Route::post('/create', [GlobalCurrencyController::class, 'store'])->name('store');
        //show one global currency route
        Route::get('/show/{currency}', [GlobalCurrencyController::class, 'show'])->name('show');
        //edit and update route
        Route::get('/edit/{currency}/', [GlobalCurrencyController::class, 'edit'])->name('edit');
        Route::post('/edit/{currency}', [GlobalCurrencyController::class, 'update'])->name('update');
        //destroy one global currency
        Route::delete('/delete/{currency}', [GlobalCurrencyController::class, 'destroy'])->name('destroy');
        //Todo:show banners with related gc
        Route::get('/show_banner_gc/{global_currency_id}', [BannerGCController::class, 'showGCWithBanners'])->name('show_banner_gc');
        Route::get('/add_banners/{global_currency_id}', [BannerGCController::class, 'selectBanners'])->name('add_banners');
        Route::post('/add_banners/{global_currency_id}', [BannerGCController::class, 'addBannerToGlobalCurrency']);
        Route::get('attach_banner/{global_currency_id}', [GlobalCurrencyController::class, 'attachBanner']);
        Route::get('/make_hidden/{global_currency_id}', [GlobalCurrencyController::class, 'makeGlobalCurrencyHidden'])->name('make_hidden');

    });

    //IntervalController
    Route::prefix('currency_change_percent')->name('currency_change_percent.')->group(function () {
        Route::get('/', [CurrencyChangeController::class, 'show'])->name('show');
        Route::get('/create', [CurrencyChangeController::class, 'create'])->name('create');
        Route::post('/create', [CurrencyChangeController::class, 'store'])->name('store');
        Route::get('/edit/{currencyChangePercent}', [CurrencyChangeController::class, 'edit'])->name('edit');
        Route::put('/edit/{currencyChangePercent}', [CurrencyChangeController::class, 'update'])->name('update');
        Route::get('/delete/{currencyChangePercent}', [CurrencyChangeController::class, 'destroy'])->name('destroy');
    });

    Route::prefix('intervals')->name('intervals.')->group(function () {
        Route::get('/', [IntervalController::class, 'show'])->name('show');
        Route::get('/create', [IntervalController::class, 'create'])->name('create');
        Route::post('/create', [IntervalController::class, 'store'])->name('store');
        Route::get('/edit/{interval}', [IntervalController::class, 'edit'])->name('edit');
        Route::put('/edit/{interval}', [IntervalController::class, 'update'])->name('update');
        Route::get('/delete/{interval}', [IntervalController::class, 'destroy'])->name('destroy');
    });

    Route::prefix('banner')->name('banner.')->group(function () {

        Route::prefix('types')->name('types.')->group(function () {
            Route::get('/', [BannerTypeController::class, 'show'])->name('show');
            Route::get('/create', [BannerTypeController::class, 'create'])->name('create');
            Route::post('/create', 'BannerTypeController@store')->name('store');
            Route::get('/edit/{bannerType}', 'BannerTypeController@edit')->name('edit');
            Route::put('/edit/{bannerType}', 'BannerTypeController@update')->name('update');
            Route::get('/delete/{bannerType}', 'BannerTypeController@destroy')->name('destroy');
        });

        Route::get('/', [BannerController::class, 'show'])->name('show');
        Route::get('active_banners', [BannerController::class, 'showActiveBanners'])->name('active');
        Route::get('create', [BannerController::class, 'create'])->name('create');
        Route::post('create', [BannerController::class, 'add']);
        Route::get('edit/{banner}', [BannerController::class, 'edit'])->name('edit');
        Route::post('edit/{banner}', [BannerController::class, 'update']);
        Route::get('edit2/{banner}', [BannerController::class, 'update2'])->name('edit2');
        Route::get('delete/{banner}', [BannerController::class, 'delete'])->name('delete');
        Route::get('toggle/{banner}', [BannerController::class, 'toggleBanners'])->name('toggle');
        Route::get('slider_toggle/{banner}', [BannerController::class, 'toggleSliderBanners'])->name('toggle-sliders');
        Route::get('add_global_currencies/{banner_id}', [BannerGCController::class, 'selectGlobalCurrencies'])->name('add_global_currencies');
        Route::post('add_global_currencies/{banner_id}', [BannerGCController::class, 'addGlobalCurrencyToBanner']);
    });

//    Route::prefix('faq')->name('faq.')->group(function () {
//
//        Route::prefix('category')->name('category.')->group(function () {
//            Route::get('/', [FaqCategoryController::class, 'show'])->name('show_categories');
//            Route::get('create', [FaqCategoryController::class, 'create'])->name('create');
//            Route::post('create', [FaqCategoryController::class, 'add']);
//            Route::get('edit/{faq_category}', [FaqCategoryController::class, 'edit'])->name('edit');
//            Route::post('edit/{faq_category}', [FaqCategoryController::class, 'update']);
//            Route::get('delete/{faq_category}', [FaqCategoryController::class, 'delete'])->name('delete');
//        });
//
//        Route::prefix('question_answer')->name('question_answer.')->group(function () {
//            Route::get('/', [FaqQuestionAnswerController::class, 'showQuestions'])->name('show_questions');
//            Route::get('create', [FaqQuestionAnswerController::class, 'create'])->name('create');
//            Route::post('create', [FaqQuestionAnswerController::class, 'add']);
//            Route::get('edit/{faq_question_answer}', [FaqQuestionAnswerController::class, 'edit'])->name('edit');
//            Route::post('edit/{faq_question_answer}', [FaqQuestionAnswerController::class, 'update'])->name('update');
//            Route::get('delete/{faq_question_answer}', [FaqQuestionAnswerController::class, 'delete'])->name('delete');
//            Route::get('/selected/{faq_question_answer}', [FaqQuestionAnswerController::class, 'showSelectedQuestion'])->name('feedback');
//
//            Route::prefix('deeplink')->name('deeplink.')->group(function () {
//                Route::get('/create/{id}', [FaqQuestionAnswerController::class, 'createDeeplink'])->name('create');
//                Route::post('/store', [FaqQuestionAnswerController::class, 'storeDeeplink'])->name('store');
//                Route::get('delete/{deeplink_id}', [FaqQuestionAnswerController::class, 'deleteDeeplink'])->name('delete');
//            });
//        });
//    });

    Route::prefix('comments')->name('comments.')->group(function () {
        Route::get('/', [CommentController::class, 'showComments'])->name('show');
        Route::get('/show/survey', [CommentController::class, 'showSurvey'])->name('survey');
        Route::get('/toggle/{comment_id}', [CommentController::class, 'toggleComment'])->name('toggle');
        Route::post('/toggle/multiple', [CommentController::class, 'toggleMultipleComment'])->name('toggle.multiple');
    });

    Route::prefix('trend')->name('trend.')->group(function () {
        Route::get('/', [TrendController::class, 'show'])->name('show');
        Route::get('/create', [TrendController::class, 'create'])->name('create');
        Route::post('/create', [TrendController::class, 'add'])->name('store');
        Route::get('/edit/{id}', [TrendController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [TrendController::class, 'update'])->name('update');

routes/web.php
<?php

use App\Http\Controllers\API\GlobalCurrencyController;
use App\Http\Controllers\GameController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StorageManagerController;
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/storage/{path}', [StorageManagerController::class, 'showFile'])
    ->where([
        'path' => '.*'
    ])
    ->name('storage.show.file');

Route::get('/exchange/getUserGame',[\App\Http\Controllers\ApiKeyController::class,'gameUser'])->name('gameUser');



Route::get('/exchange/tv_market_global2/{symbol}', [GlobalCurrencyController::class, 'tradingViewBySymbol'])->middleware('s_cache:300');
Route::get('/exchange/tv_market/{pair_id}', [GlobalCurrencyController::class, 'tradingViewByPairId'])->middleware('s_cache:300');
Route::get('exchange/pt1/market',[\App\Http\Controllers\VueController::class,'pwaIndex']);
Route::pattern('ex', '.*');
Route::any('/pt{ex}', [\App\Http\Controllers\VueController::class, 'pwaIndex'])->name('pwa_index');
Route::get('play', function () {
    return redirect('https://ramzinex.com/');
});
Route::prefix('comments_report')->name('comments_report.')->group(function () {
//    Route::get('/report', [CommentController::class, 'getCommentReplies'])->middleware('s_cache:300')->name('report.list');
    Route::POST('/create', [\App\Http\Controllers\API\CommentReportController::class, 'create'])->name('create');
//    Route::POST('/dislike', [CommentController::class, 'dislikeComments'])->name('dislike');
});

Route::pattern('ex', '.*');
Route::any('/register_with_invitation={ex}', [\App\Http\Controllers\ExcelController::class, 'test'])->name('test*');

//Route::pattern('ex', '.*');
Route::get('/test_new_url',[\App\Http\Controllers\ExcelController::class, 'testUrl'])->name('test**');

//Route::get('hiiii',[\App\Http\Controllers\ExcelController::class,'testUrl']);
Route::get('/testLock1',[\App\Http\Controllers\ApiKeyController::class, 'test1'])->name('test1');
Route::get('/testLock2',[\App\Http\Controllers\ApiKeyController::class, 'test2'])->name('test2');
Route::get('/rrrr',function (){
    return 'hii';
})->name('test3');

app/Http/Controllers/API2/CommentController.php
<?php

namespace App\Http\Controllers\API2;

use App\Factories\CommentRepoFactory;
use App\Http\Controllers\Controller;
use App\Http\Requests\Api2\Comment\CommentReplies;
use App\Http\Resources\Comments;
use App\Repositories\Interfaces\CommentRepositoryInterface;
use App\Services\UserAuthentication\UserAuthenticatorService;
use Illuminate\Http\Resources\Json\AnonymousResourceCollection;

class CommentController extends Controller
{

    /**
     * User Authenticator Service container
     * @var UserAuthenticatorService
     */
    protected UserAuthenticatorService $user_authenticator_service;
    /**
     * CommentRepository Container
     * @var CommentRepositoryInterface
     */
    private CommentRepositoryInterface $comment_repository;


    /**
     * Construct and inject necessary services to their container
     * @param UserAuthenticatorService $user_authenticator_service
     */
    public function __construct(UserAuthenticatorService $user_authenticator_service)
    {
        $this->comment_repository= CommentRepoFactory::createRepository('comment_version_two');
        $this->user_authenticator_service = $user_authenticator_service;
    }

    /**
     * Get and return comment replies
     * @param CommentReplies $request
     * @return AnonymousResourceCollection
     */
    public function getCommentReplies(CommentReplies $request): AnonymousResourceCollection
    {
        $depth_id = $request->input('depth_id');
        $from = $request->input('offset', 0);
        $take = $request->input('limit', 10);
        $type = $request->input('type','comment');
        if ($request->hasHeader('Authorization')) {
            $user_id = $this->user_authenticator_service->getUserId($request);
        }
        $comments = $this->comment_repository->getAllComment(null, false, true, $from, $take, true, $depth_id, $user_id ?? null,$type);
        $comment_counts = $this->comment_repository->getCommentsCount(null, true, $depth_id);
        return Comments::collection($comments)->additional([
            'status' => 0,
            'count' => $comment_counts
        ]);
    }

}

resources/views/comment/edit.blade.php
@extends('layouts.appAdmin')

@section('title', 'ویرایش')

@section('desktop')

    @if (count($errors) > 0)
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    @endif
    <!DOCTYPE html>
    <html>

    <head>
        <script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
        <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    </head>


    <div class="row">
        <div class="col-xlg-15 col-lg-15">
            <div class="panelGlass minH-240">
                <form action="{{route('comments.edit',[$comment->id])}}" method="POST"
                      class="form-inline" enctype="multipart/form-data">
                    {{csrf_field()}}

                    <div class="form-group pa-10">
                        <label for="commentable_id">بنر مربوطه</label>
                        <select class="form-control" name="commentable_id">

                                <option @if($related_model->id == $comment->commentable_id) selected="selected"
                                        @endif value="{{$comment->commentable->id}}">
                                    {{$related_model->title_fa}}
                                </option>

                        </select>
                    </div>
                    <div class="form-group pa-10">
                        <label class="control-label mb-10"
                               for="body">کامنت </label>
                        <textarea rows="4" cols="50"
                                  name="body"  id="text-editor"
                                  class="form-control">
                            {{$comment->body}}

                        </textarea>
                    </div>


                    <div class="col-md-12 pa-20 text-center">
                        <div class="form-actions mt-10">
                            <button id="update-profile" type="submit"
                                    class="btn btn-primary mr-10 mb-30">
                                ثبت تغییرات
                            </button>
                        </div>
                    </div>
                </form>
            </div>
        </div>
    </div>
    <script>
        ClassicEditor
            .create(document.querySelector('#text-editor'))
            .catch(error => {
                console.error(error);
            });
    </script>
@endsection

resources/views/comment/reply.blade.php
@extends('layouts.appAdmin')

@section('title','ویرایش')

@section('desktop')

{{--    @if (count($errors) > 0)--}}
{{--        @foreach ($errors->all() as $error)--}}
{{--            <li>{{ $error }}</li>--}}
{{--        @endforeach--}}
{{--    @endif--}}
    <!DOCTYPE html>
    <html>

    <head>
        <script src="https://cdn.ckeditor.com/ckeditor5/26.0.0/classic/ckeditor.js"></script>
        <script src="/vendor/unisharp/laravel-ckeditor/ckeditor.js"></script>
    </head>

    <div class="row">
        <div class="col-xlg-15 col-lg-15">
            <div class="panelGlass minH-240">
{{--                <form action="{{route('comment.reply',[$commentable_id,$comment_id])}}" method="POST"--}}
                      class="form-inline" enctype="multipart/form-data">
                    {{csrf_field()}}
                    <div class="form-group pa-10">
                        <label class="control-label mb-10"
                               for="body">ریپلای</label>
                        <textarea rows="4" cols="50" placeholder="ریپلای ..."
                                  name="body"  id="text-editor"
                                  class="form-control"></textarea>
                    </div>
{{--                    <input type="hidden" name="commentable_id" value="{{$commentable_id}}">--}}
{{--                    <input type="hidden" name="comment_id" value="{{$comment_id}}">--}}

                    <div class="col-md-12 pa-20 text-center">
                        <div class="form-actions mt-10">
                            <button id="update-profile" type="submit"
                                    class="btn btn-primary mr-10 mb-30">
                                ثبت پاسخ
                            </button>
                        </div>
                    </div>
{{--                </form>--}}
            </div>
        </div>
    </div>
    <script>
        ClassicEditor
            .create(document.querySelector('#text-editor'))
            .catch(error => {
                console.error(error);
            });
    </script>
@endsection

resources/views/comment/show.blade.php
@extends('layouts.appAdmin')
@section('title', 'نمایش')

@section('desktop')
    @if (count($errors) > 0)
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    @endif
    @if (session('success'))
        <div class="alert alert-success">
            {{ session('success') }}
        </div>
    @elseif (session('error'))
        <div class="alert-danger">
            {{ session('error') }}
        </div>
    @endif
    <head>
        <style>
            button.like {
                width: 30px;
                height: 30px;
                margin: 0 auto;
                line-heigth: 50px;
                border-radius: 50%;
                color: rgba(0, 150, 136, 1);
                background-color: rgba(38, 166, 154, 0.3);
                border-color: rgba(0, 150, 136, 1);
                border-width: 1px;
                font-size: 15px;
            }

            button.dislike {
                width: 30px;
                height: 30px;
                margin: 0 auto;
                line-heigth: 50px;
                border-radius: 50%;
                color: rgba(255, 82, 82, 1);
                background-color: rgba(255, 138, 128, 0.3);
                border-color: rgba(255, 82, 82, 1);
                border-width: 1px;
                font-size: 15px;
            }

            button.learnmore {
                width: 100%;
                padding: 10px;
                border: none;
                background: rgba(0, 151, 167, 1);
                border-radius: 5px;
                text-transform: uppercase;
                font-size: 16px;
                color: #fff;
                letter-spacing: 1px;
            }

            #image {
                height: 200px;
                width: 500px;
                padding: 5px;

            }
        </style>
    </head>
    <div class="row">
        <div class="col-xlg-12 col-lg-12">
            <div class="panelGlass minH-240">
                <div>
                    <table id="bonusTable" class="table mediumThead">
                        <div class="row">
                            <div class="form-wrap">
                                <thead>
                                <tr>
                                    <th scope="col">نام کاربری</th>
                                    <th scope="col">نام مستعار</th>
                                    <th scope="col">نوع</th>
                                    <th scope="col">عنوان</th>
                                    <th scope="col">کامنت والد</th>
                                    <th scope="col"> کامنت</th>
                                    <th scope="col">عکس</th>
                                    <th scope="col">vot options</th>
                                    <th scope="col">نوع کامنت</th>
                                    <th scope="col">استاتوس</th>
                                    <th scope="col">انتخاب</th>
                                    <th>
                                </tr>
                                </thead>
                                <form action="{{ route('admin.comments.toggle.multiple') }}"
                                      enctype="multipart/form-data" method="post">
                                    @csrf
                                    <tbody>
                                    @foreach($comments as $comment)
                                        <tr>
                                            <td class="text-sm">{{$comment->user->sid}}</td>
                                            <td class="text-sm">{{$comment->nickname ?? '-'}}</td>
{{--                                            <td class="text-sm">{{$comment->comment_type['type']}}</td>--}}
                                            <td class="text-sm">
                                                @if(isset($comment->commentable->name_en))
                                                    {{$comment->commentable->name_en}}
                                                @elseif(isset($comment->commentable->title))
                                                    {{$comment->commentable->title['fa']}}
                                                @elseif(isset($comment->commentable->question))
                                                    {{$comment->commentable->question['fa']}}
                                                @endif
                                            </td>
                                            <td class="text-sm">
                                                @if($comment->comment)
                                                    {!!$comment->comment->body!!}
                                                @endif
                                            </td>
                                            <td class="text-sm"> {!! $comment->body !!} </td>
                                            <td>

                                                @if(isset($comment->file))
                                                    <div class="row">
                                                        <div class="col-sm-5">
                                                            <img width="20px" id="image" src="{{$comment->file->path}}">
                                                        </div>
                                                    </div>
                                                @endif
                                            </td>
                                            <td>
                                                @if(isset($comment->options))
                                                    <div class="row">
                                                        @foreach($comment->options as $option)
                                                            <span class="badge badge-light">{{$option}}</span>
                                                        @endforeach
                                                    </div>
                                                @endif
                                            </td>
                                            <td class="text-sm">{{$comment->type}}</td>

                                            <td>
                                                <div class="row">
                                                    <div class="col-sm-10">
                                                        <a class="btn btn-primary"
                                                           @if($comment->status == 1)href="{{route('admin.comments.toggle',[$comment->id])}}"
                                                           disabled
                                                           @endif  href="{{route('admin.comments.toggle',[$comment->id])}}">
                                                            @if($comment->status == 1)غیرفعال
                                                            @else فعال
                                                            @endif
                                                        </a>
                                                    </div>
                                                </div>
                                            </td>
                                            {{--                                            <td class="text-sm">
                                                                                            <a href="{{route('comment.edit',[$comment->id])}}"
                                                                                               class="btn btn-primary">ویرایش</a>
                                                                                            <a href="{{route('comment.delete',[$comment->id])}}"
                                                                                               class="btn btn-danger">حذف</a>
                                                                                            <a href="{{route('comment.reply',[$comment->commentable_id,$comment->id])}}"
                                                                                               class="btn btn-success">ریپلای</a>
                                                                                        </td>--}}
                                            <td>
                                                @if($comment->status != 1)
                                                    <div class="row">
                                                        <div class="col-sm-10">
                                                            <input type="checkbox" name="comments[]"
                                                                   value="{{$comment->id}}"/>
                                                        </div>
                                                    </div>
                                                @endif
                                            </td>
                                        </tr>
                                    @endforeach
                                    </tbody>
                                    <button type="submit" class="btn btn-primary">تایید کامنت های انتخاب شده</button>
                                </form>
                            </div>
                        </div>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {{$comments->links()}}
@endsection