routes/admin.php
<?php

use App\Http\Controllers\Admin\BannerGCController;
use App\Http\Controllers\Admin\CurrencyOHLCController;
use App\Http\Controllers\Admin\GainerController;
use App\Http\Controllers\Admin\LooserController;
use App\Http\Controllers\Admin\TrendController;
use App\Http\Controllers\Admin\TrendingCurrencyController;
use App\Http\Controllers\Admin\CurrencyController;
use App\Http\Controllers\GameController;
use App\Jobs\UpdateLeftOverGlobalCurrenciesJob;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\Admin\Auth\AuthenticatedSessionController;
use App\Http\Controllers\Admin\GlobalCurrencyController;
use App\Http\Controllers\CurrencyChangeController;
use App\Http\Controllers\IntervalController;
use App\Http\Controllers\Admin\BannerController;
use App\Http\Controllers\Admin\BannerTypeController;
use App\Http\Controllers\Admin\AdminController;
use App\Http\Controllers\Admin\CommentController;
use App\Http\Controllers\TagController;
use App\Http\Controllers\Admin\GCurrencyInfoController;
use App\Http\Controllers\FaqQuestionAnswerController;
use App\Http\Controllers\FaqCategoryController;

//Todo Add more security
Route::get('/login', [AuthenticatedSessionController::class, 'create'])
    ->middleware('guest')
    ->name('admin.login');

Route::post('/login', [AuthenticatedSessionController::class, 'store'])
    ->middleware('guest');

/** Authenticated user sections */
Route::prefix('panel')->middleware(['is_authenticated'])->name('admin.')->group(function () {
    Route::get('/logout', [AuthenticatedSessionController::class, 'destroy'])
        ->name('logout');
    Route::get('/dashboard', [AdminController::class, 'index'])->name('dashboard');
    Route::prefix('game')->group(function () {
        //show all game users
        Route::get('/users', [GameController::class, 'users'])->name('game-users.index');
        Route::get('/scores/{user}', [GameController::class, 'scores'])->name('game-users.scores');
        Route::delete('/scores/delete/{score}', [GameController::class, 'deleteScores'])->name('game-users.scores.destroy');

    });

    Route::prefix('global-currencies')->name('global-currencies.')->group(function () {
        //show all global currencies
        Route::get('/', [GlobalCurrencyController::class, 'index'])->name('index');
        //create and store route
        Route::get('/create', [GlobalCurrencyController::class, 'create'])->name('create');
        Route::post('/create', [GlobalCurrencyController::class, 'store'])->name('store');
        //show one global currency route
        Route::get('/show/{currency}', [GlobalCurrencyController::class, 'show'])->name('show');
        //edit and update route
        Route::get('/edit/{currency}/', [GlobalCurrencyController::class, 'edit'])->name('edit');
        Route::post('/edit/{currency}', [GlobalCurrencyController::class, 'update'])->name('update');
        //destroy one global currency
        Route::delete('/delete/{currency}', [GlobalCurrencyController::class, 'destroy'])->name('destroy');
        //Todo:show banners with related gc
        Route::get('/show_banner_gc/{global_currency_id}', [BannerGCController::class, 'showGCWithBanners'])->name('show_banner_gc');
        Route::get('/add_banners/{global_currency_id}', [BannerGCController::class, 'selectBanners'])->name('add_banners');
        Route::post('/add_banners/{global_currency_id}', [BannerGCController::class, 'addBannerToGlobalCurrency']);
        Route::get('attach_banner/{global_currency_id}', [GlobalCurrencyController::class, 'attachBanner']);
        Route::get('/make_hidden/{global_currency_id}', [GlobalCurrencyController::class, 'makeGlobalCurrencyHidden'])->name('make_hidden');

    });

    //IntervalController
    Route::prefix('currency_change_percent')->name('currency_change_percent.')->group(function () {
        Route::get('/', [CurrencyChangeController::class, 'show'])->name('show');
        Route::get('/create', [CurrencyChangeController::class, 'create'])->name('create');
        Route::post('/create', [CurrencyChangeController::class, 'store'])->name('store');
        Route::get('/edit/{currencyChangePercent}', [CurrencyChangeController::class, 'edit'])->name('edit');
        Route::put('/edit/{currencyChangePercent}', [CurrencyChangeController::class, 'update'])->name('update');
        Route::get('/delete/{currencyChangePercent}', [CurrencyChangeController::class, 'destroy'])->name('destroy');
    });

    Route::prefix('intervals')->name('intervals.')->group(function () {
        Route::get('/', [IntervalController::class, 'show'])->name('show');
        Route::get('/create', [IntervalController::class, 'create'])->name('create');
        Route::post('/create', [IntervalController::class, 'store'])->name('store');
        Route::get('/edit/{interval}', [IntervalController::class, 'edit'])->name('edit');
        Route::put('/edit/{interval}', [IntervalController::class, 'update'])->name('update');
        Route::get('/delete/{interval}', [IntervalController::class, 'destroy'])->name('destroy');
    });

    Route::prefix('banner')->name('banner.')->group(function () {

        Route::prefix('types')->name('types.')->group(function () {
            Route::get('/', [BannerTypeController::class, 'show'])->name('show');
            Route::get('/create', [BannerTypeController::class, 'create'])->name('create');
            Route::post('/create', 'BannerTypeController@store')->name('store');
            Route::get('/edit/{bannerType}', 'BannerTypeController@edit')->name('edit');
            Route::put('/edit/{bannerType}', 'BannerTypeController@update')->name('update');
            Route::get('/delete/{bannerType}', 'BannerTypeController@destroy')->name('destroy');
        });

        Route::get('/', [BannerController::class, 'show'])->name('show');
        Route::get('active_banners', [BannerController::class, 'showActiveBanners'])->name('active');
        Route::get('create', [BannerController::class, 'create'])->name('create');
        Route::post('create', [BannerController::class, 'add']);
        Route::get('edit/{banner}', [BannerController::class, 'edit'])->name('edit');
        Route::post('edit/{banner}', [BannerController::class, 'update']);
        Route::get('edit2/{banner}', [BannerController::class, 'update2'])->name('edit2');
        Route::get('delete/{banner}', [BannerController::class, 'delete'])->name('delete');
        Route::get('toggle/{banner}', [BannerController::class, 'toggleBanners'])->name('toggle');
        Route::get('slider_toggle/{banner}', [BannerController::class, 'toggleSliderBanners'])->name('toggle-sliders');
        Route::get('add_global_currencies/{banner_id}', [BannerGCController::class, 'selectGlobalCurrencies'])->name('add_global_currencies');
        Route::post('add_global_currencies/{banner_id}', [BannerGCController::class, 'addGlobalCurrencyToBanner']);
    });

//    Route::prefix('faq')->name('faq.')->group(function () {
//
//        Route::prefix('category')->name('category.')->group(function () {
//            Route::get('/', [FaqCategoryController::class, 'show'])->name('show_categories');
//            Route::get('create', [FaqCategoryController::class, 'create'])->name('create');
//            Route::post('create', [FaqCategoryController::class, 'add']);
//            Route::get('edit/{faq_category}', [FaqCategoryController::class, 'edit'])->name('edit');
//            Route::post('edit/{faq_category}', [FaqCategoryController::class, 'update']);
//            Route::get('delete/{faq_category}', [FaqCategoryController::class, 'delete'])->name('delete');
//        });
//
//        Route::prefix('question_answer')->name('question_answer.')->group(function () {
//            Route::get('/', [FaqQuestionAnswerController::class, 'showQuestions'])->name('show_questions');
//            Route::get('create', [FaqQuestionAnswerController::class, 'create'])->name('create');
//            Route::post('create', [FaqQuestionAnswerController::class, 'add']);
//            Route::get('edit/{faq_question_answer}', [FaqQuestionAnswerController::class, 'edit'])->name('edit');
//            Route::post('edit/{faq_question_answer}', [FaqQuestionAnswerController::class, 'update'])->name('update');
//            Route::get('delete/{faq_question_answer}', [FaqQuestionAnswerController::class, 'delete'])->name('delete');
//            Route::get('/selected/{faq_question_answer}', [FaqQuestionAnswerController::class, 'showSelectedQuestion'])->name('feedback');
//
//            Route::prefix('deeplink')->name('deeplink.')->group(function () {
//                Route::get('/create/{id}', [FaqQuestionAnswerController::class, 'createDeeplink'])->name('create');
//                Route::post('/store', [FaqQuestionAnswerController::class, 'storeDeeplink'])->name('store');
//                Route::get('delete/{deeplink_id}', [FaqQuestionAnswerController::class, 'deleteDeeplink'])->name('delete');
//            });
//        });
//    });

    Route::prefix('comments')->name('comments.')->group(function () {
        Route::get('/', [CommentController::class, 'showComments'])->name('show');
        Route::get('/show/survey', [CommentController::class, 'showSurvey'])->name('survey');
        Route::get('/toggle/{comment_id}', [CommentController::class, 'toggleComment'])->name('toggle');
        Route::post('/toggle/multiple', [CommentController::class, 'toggleMultipleComment'])->name('toggle.multiple');
    });

    Route::prefix('trend')->name('trend.')->group(function () {
        Route::get('/', [TrendController::class, 'show'])->name('show');
        Route::get('/create', [TrendController::class, 'create'])->name('create');
        Route::post('/create', [TrendController::class, 'add'])->name('store');
        Route::get('/edit/{id}', [TrendController::class, 'edit'])->name('edit');
        Route::post('/edit/{id}', [TrendController::class, 'update'])->name('update');

routes/web.php
<?php

use App\Http\Controllers\API\GlobalCurrencyController;
use App\Http\Controllers\GameController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StorageManagerController;
use Illuminate\Http\Request;


/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/storage/{path}', [StorageManagerController::class, 'showFile'])
    ->where([
        'path' => '.*'
    ])
    ->name('storage.show.file');

Route::get('/exchange/getUserGame',[\App\Http\Controllers\ApiKeyController::class,'gameUser'])->name('gameUser');



Route::get('/exchange/tv_market_global2/{symbol}', [GlobalCurrencyController::class, 'tradingViewBySymbol'])->middleware('s_cache:300');
Route::get('/exchange/tv_market/{pair_id}', [GlobalCurrencyController::class, 'tradingViewByPairId'])->middleware('s_cache:300');
Route::get('exchange/pt1/market',[\App\Http\Controllers\VueController::class,'pwaIndex']);
Route::pattern('ex', '.*');
Route::any('/pt{ex}', [\App\Http\Controllers\VueController::class, 'pwaIndex'])->name('pwa_index');
Route::get('play', function () {
    return redirect('https://ramzinex.com/');
});
Route::prefix('comments_report')->name('comments_report.')->group(function () {
//    Route::get('/report', [CommentController::class, 'getCommentReplies'])->middleware('s_cache:300')->name('report.list');
    Route::POST('/create', [\App\Http\Controllers\API\CommentReportController::class, 'create'])->name('create');
//    Route::POST('/dislike', [CommentController::class, 'dislikeComments'])->name('dislike');
});

Route::pattern('ex', '.*');
Route::any('/register_with_invitation={ex}', [\App\Http\Controllers\ExcelController::class, 'test'])->name('test*');

//Route::pattern('ex', '.*');
Route::get('/test_new_url',[\App\Http\Controllers\ExcelController::class, 'testUrl'])->name('test**');

//Route::get('hiiii',[\App\Http\Controllers\ExcelController::class,'testUrl']);
Route::get('/testLock1',[\App\Http\Controllers\ApiKeyController::class, 'test1'])->name('test1');
Route::get('/testLock2',[\App\Http\Controllers\ApiKeyController::class, 'test2'])->name('test2');
Route::get('/rrrr',function (){
    return 'hii';
})->name('test3');

app/Models/Interval.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;
use Illuminate\Database\Eloquent\Relations\HasMany;

/**
 * @property string title_en
 * @property string title_fa
 */
class Interval extends Model
{
    /**
     * The attributes that are mass assignable.
     *
     * @var string[]
     */
    protected $fillable = ['title_fa','title_en'];

    /**
     * The database connection that should be used by the migration.
     *
     * @var string
     */
    protected $table = 'intervals';

    /**
     * Disable timestamps in model
     * @var bool
     */
    public $timestamps = false;

    /**
     * Get all of the currency_change_percent for the interval.
     *
     * @return HasMany
     */
    public function currencyChange():HasMany
    {
        return $this->hasMany(CurrencyChangesPercent::class, 'interval_id', 'id');
    }

    /**
     * return daily interval id
     * @return int
     */
    public static function getDailyId(): int //Todo Make getting Id's more dynamic
    {
        return 1;
    }

    /**
     * return weekly interval id
     * @return int
     */
    public static function getWeeklyId(): int //Todo Make getting Id's more dynamic
    {
        return 2;
    }

    /**
     * return monthly interval id
     * @return int
     */
    public static function getMonthlyId(): int //Todo Make getting Id's more dynamic
    {
        return 3;
    }

    /**
     * return yearly interval id
     * @return int
     */
    public static function getYearlyId(): int //Todo Make getting Id's more dynamic
    {
        return 4;
    }
}

app/Http/Controllers/IntervalController.php
<?php

namespace App\Http\Controllers;

use App\Repositories\Interfaces\IntervalRepositoryInterface;
use App\Http\Requests\Interval\Store;
use App\Http\Requests\Interval\Update;
use Illuminate\Http\RedirectResponse;
use Illuminate\View\View;

class IntervalController extends Controller
{
    /**
     * The interval repository instance.
     *
     * @var IntervalRepositoryInterface
     */
    private IntervalRepositoryInterface $interval_repository;

    /**
     * Instantiate a new interval instance.
     *
     * @param IntervalRepositoryInterface $interval_repository
     */
    public function __construct(IntervalRepositoryInterface $interval_repository)
    {
        $this->interval_repository = $interval_repository;
    }

    /**
     * Display a listing of the resource.
     *
     * @return View
     */
    public function show(): View
    {
        $intervals = $this->interval_repository->paginate();
        return view('interval.show', compact('intervals'));
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return View
     */
    public function create(): View
    {
        return view('interval.create');
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param int $id
     * @return View
     */
    public function edit(int $id): view
    {
        $intervals = $this->interval_repository->findById($id);
        return view('interval.edit', compact('intervals'));
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param Store $store
     * @return RedirectResponse
     */
    public function store(Store $store): RedirectResponse
    {
        $input = $store->only('title_fa', 'title_en');
        $result = $this->interval_repository->store($input);
        if (!$result) {
            return redirect()->back()->with('error', 'عملیات ذخیره سازی با شکست مواجه شد.');
        }
        return redirect()->route('admin.intervals.show')
            ->with('success', 'عملیات ذخیره سازی با موفقیت انجام شد.');
    }

    /**
     * Update the specified resource in storage.
     *
     * @param int $id
     * @param Update $update
     * @return RedirectResponse
     */
    public function update(int $id, Update $update): RedirectResponse
    {
        $intervals = $this->interval_repository->findById($id);
        $input = $update->only('title_fa', 'title_en');
        $result = $this->interval_repository->update($input, $intervals);
        if (!$result) {
            return redirect()->back()->with('error', 'عملیات بروزرسانی با شکست مواجه شد.');
        }
        return redirect()->route('admin.intervals.show')
            ->with('success', 'عملیات بروزرسانی با موفقیت انجام شد.');
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param int $id
     * @return RedirectResponse
     */
    public function destroy(int $id): RedirectResponse
    {
        $intervals = $this->interval_repository->findById($id);
        $result = $this->interval_repository->delete($intervals);

        if (!$result) {
            return redirect()->back()->with('error', 'عملیات حذف با شکست مواجه شد.');
        }

        return redirect()->back()->with('success', 'عملیات حذف با موفقیت انجام شد.');
    }
}

resources/views/interval/create.blade.php
@extends('layouts.appAdmin')
@section('title', 'ایجاد اینتروال جدید')

@section('desktop')

    @if ( count($errors) > 0)
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    @endif
    @if (session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif
    @if ( session()->has('error'))
        <div class="alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif

<div class="row">
    <div class="col-xlg-12 col-lg-12">
        <div class="panelGlass minH-240">
             <form action="{{route('admin.intervals.create')}}" method="POST"  class="form-inline" >

                 {{csrf_field()}}

                 <div class="form-group pa-10">
                     <label for="title">عنوان اینتروال فارسی</label>
                     <input type="text" class="form-control"
                            name="title_fa" id="title"
                            placeholder="عنوان اینتروال ...">
                 </div>
                 <div class="form-group pa-10">
                     <label for="title">عنوان اینتروال انگلیسی</label>
                     <input type="text" class="form-control"
                            name="title_en" id="title"
                            placeholder="عنوان اینتروال ...">
                 </div>

                 <div class="col-md-12 pa-20 text-center">
                     <div class="form-actions mt-10">
                         <button id="update-profile" type="submit"
                                 class="btn btn-primary mr-10 mb-30">
                             ایجاد اینتروال
                         </button>
                     </div>
                </div>

              </form>
            </div>
        </div>
    </div>

@endsection

resources/views/interval/edit.blade.php
@extends('layouts.appAdmin')
@section('title', 'ویرایش اینتروال')

@section('desktop')

    @if ( count($errors) > 0)
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    @endif
    @if (session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif
    @if ( session()->has('error'))
        <div class="alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif

<div class="row">
    <div class="col-xlg-15 col-lg-15">
        <div class="panelGlass minH-240">
                    <form action="{{route('admin.intervals.update',[$intervals->id])}}" method="POST" class="form-inline" >

                        {{csrf_field()}}

                        @method('PUT')

                        <div class="form-wrap">

                            <div class="form-group pa-10">
                                <label class="control-label mb-10"
                                       for="title"> عنوان اینتروال فارسی</label>
                                <input type="text" class="form-control"
                                       name="title_fa" id="title"
                                       value="{{$intervals->title_fa}}">
                            </div>
                            <div class="form-group pa-10">
                                <label class="control-label mb-10"
                                       for="title">عنوان اینتروال انگلیسی</label>
                                <input type="text" class="form-control"
                                       name="title_en" id="title"
                                       value="{{$intervals->title_en}}">
                            </div>

                            <div class="col-md-12 pa-20 text-center">
                                <div class="form-actions mt-10">
                                    <button id="update-profile" type="submit"
                                            class="btn btn-primary mr-10 mb-30">
                                     ثبت تغییرات
                                    </button>
                                </div>
                            </div>

                        </div>

                    </form>
                </div>
            </div>
        </div>
@endsection

resources/views/interval/show.blade.php
@extends('layouts.appAdmin')
@section('title', 'نمایش لیست اینتروال ها')

@section('desktop')

    @if ( count($errors) > 0)
        @foreach ($errors->all() as $error)
            <li>{{ $error }}</li>
        @endforeach
    @endif
    @if (session()->has('success'))
        <div class="alert alert-success">
            {{ session()->get('success') }}
        </div>
    @endif
    @if ( session()->has('error'))
        <div class="alert-danger">
            {{ session()->get('error') }}
        </div>
    @endif

    <div class="row">
        <div class="col-xlg-12 col-lg-12">
            <div class="panelGlass minH-240">
                <div>
                    <table id="bonusTable" class="table mediumThead">
                        <div class="row">
                            <div class="form-wrap">

                                <thead>
                                    <tr>
                                        <th scope="col">عنوان اینتروال</th>
                                        <th>
                                            <a href="{{route('admin.intervals.create')}}" class="btn btn-primary">ایجاد اینتروال</a>
                                        </th>
                                    </tr>
                                </thead>

                                <tbody>
                                    @foreach($intervals as $interval)
                                     <tr>
                                         <td class="text-sm">{{$interval->title_fa}}</td>
                                         <td class="text-sm">{{$interval->title_en}}</td>
                                         <td class="text-sm">
                                             <a href="{{route('admin.intervals.update',[$interval->id])}}" class="btn btn-primary">ویرایش</a>

                                             <a href="{{route('admin.intervals.destroy',[$interval->id])}}"
                                                onclick="return confirm('آیا مایل به حذف این فیلد هستید؟')" class="btn btn-danger">حذف</a>
                                         </td>
                                    </tr>
                                    @endforeach
                                </tbody>
                            </div>
                        </div>
                    </table>
                </div>
            </div>
        </div>
    </div>
    {{$intervals->links()}}
@endsection